### ISSUE TITLE
.NET Core 3.1 error with version 3.1.0 or newer

### ISSUE THREAD

**Issue by tranthaibinh111** [mihirdilip/aspnetcore-authentication-apikey#18]
when I upgrade 2.2.0 to a newer then error "Invalid API Key provided by IApiKeyProvider".

Please help me.

**Comment by mihirdilip** [comment]
@tranthaibinh111 , when returning back IApiKey from IApiKeyProvider.ProvideAsync(string key) are you returning the same key passed as method parameter as IApiKey.Key? Because, with 3.1.0 introduces extra check of this field (IApiKey.Key) against the key passed in Header/QueryParam. If it is really a problem for you, then you can set ApiKeyOptions.[ForLegacyIgnoreExtraValidatedApiKeyCheck](https://github.com/mihirdilip/aspnetcore-authentication-apikey/tree/master#forlegacyignoreextravalidatedapikeycheck)  to true on Startup.cs

I hope this helps. If you still have any issues, please send some code snippet as I am just guessing what the problem could be.

**Comment by tranthaibinh111** [comment]
@mihirdilip ,
I understand and set ApiKeyOptions.ForLegacyIgnoreExtraValidatedApiKeyCheck to true on Startup.cs. It worked.
Thanks very much!
