### ISSUE TITLE
If I use JwtBearer authentication together with ApiKey it always commands JwtBearer and authentication fails

### ISSUE THREAD

**Issue by afazio82** [mihirdilip/aspnetcore-authentication-apikey#30]
I'm probably doing something wrong.
By removing the JwtBearer authentication code, the ApiKey works

// Authentication APIKEY
builder.Services.AddTransient<IApiKeyRepository, InMemoryApiKeyRepository>();
builder.Services.AddAuthentication(ApiKeyDefaults.AuthenticationScheme)
    .AddApiKeyInHeaderOrQueryParams<ApiKeyProvider>(options =>
    {
        options.Realm = "Sample Web API";
        options.KeyName = "X-API-KEY";
    });

// Authentication JwtBearer
builder.Services.AddAuthentication(
    options =>
    {
        options.DefaultAuthenticateScheme = JwtBearerDefaults.AuthenticationScheme;
        options.DefaultChallengeScheme = JwtBearerDefaults.AuthenticationScheme;
        options.DefaultScheme = JwtBearerDefaults.AuthenticationScheme;
    }).AddJwtBearer(options =>
    {
        options.RequireHttpsMetadata = false;
        options.SaveToken = true;
        options.TokenValidationParameters = new TokenValidationParameters
        {
            ValidateIssuerSigningKey = true,
            ValidateIssuer = true,
            ValidateAudience = true,
            ValidIssuer = JWTsettings.ValidIssuer,
            ValidAudience = JWTsettings.ValidAudience,
            IssuerSigningKey = new SymmetricSecurityKey(Encoding.UTF8.GetBytes(JWTsettings.Key))
        };
    });

**Comment by mihirdilip** [comment]
It may be because you are using 2 AddAuthentication and the last one added is being used. Refer to using [multiple schemes here](https://github.com/mihirdilip/aspnetcore-authentication-apikey#multiple-authentication-schemes) and try something like below..

builder.Services.AddAuthentication(
options =>
{
options.DefaultAuthenticateScheme = JwtBearerDefaults.AuthenticationScheme;
options.DefaultChallengeScheme = JwtBearerDefaults.AuthenticationScheme;
options.DefaultScheme = JwtBearerDefaults.AuthenticationScheme;
}).AddJwtBearer(JwtBearerDefaults.AuthenticationScheme, options =>
{
options.RequireHttpsMetadata = false;
options.SaveToken = true;
options.TokenValidationParameters = new TokenValidationParameters
{
ValidateIssuerSigningKey = true,
ValidateIssuer = true,
ValidateAudience = true,
ValidIssuer = JWTsettings.ValidIssuer,
ValidAudience = JWTsettings.ValidAudience,
IssuerSigningKey = new SymmetricSecurityKey(Encoding.UTF8.GetBytes(JWTsettings.Key))
};
})
.AddApiKeyInHeaderOrQueryParams(ApiKeyDefaults.AuthenticationScheme, options =>
{
options.Realm = "Sample Web API";
options.KeyName = "X-API-KEY";
});

**Comment by afazio82** [comment]
no way....
also in this way it always commands JwtBearer authentication. 
Apikey authentication is completely ignored

**Comment by mihirdilip** [comment]
I don't know how you are authorizing your request and against what scheme. I would be able to help if you could send the code snippet for when you want to use JWT and for what requests you want to use APIKey.

Also refer to this issue #20 . It might help. Although it is using 2 different types of AddApiKey schemes, imagine one as your JWT and one as ApiKey. https://github.com/mihirdilip/aspnetcore-authentication-apikey/issues/20

**Comment by afazio82** [comment]
I solved the problem.
I set up in multiple scheme like so:

builder.Services.AddAuthentication(
    options =>
    {
        options.DefaultAuthenticateScheme = JwtBearerDefaults.AuthenticationScheme;
        options.DefaultChallengeScheme = JwtBearerDefaults.AuthenticationScheme;
        options.DefaultScheme = JwtBearerDefaults.AuthenticationScheme;
    }).AddJwtBearer("JwtBearer", options =>
    {
        options.RequireHttpsMetadata = false;
        options.SaveToken = true;
        options.TokenValidationParameters = new TokenValidationParameters
        {
            ValidateIssuerSigningKey = true,
            ValidateIssuer = true,
            ValidateAudience = true,
            ValidIssuer = JWTsettings.ValidIssuer,
            ValidAudience = JWTsettings.ValidAudience,
            IssuerSigningKey = new SymmetricSecurityKey(Encoding.UTF8.GetBytes(JWTsettings.Key))
        };
    })
    .AddApiKeyInHeaderOrQueryParams<ApiKeyProvider>("ApiKey", options =>
    {
        options.Realm = "Sample Web API";
        options.KeyName = "X-API-KEY";
    });
    
    
    
    
    Also in the controller I have set the schemes that that controller can use:
    
    [Authorize(AuthenticationSchemes = "JwtBearer,ApiKey")]

**Comment by mihirdilip** [comment]
That's one another way of achieving it. Good to know that you solved the problem. :)
